name: Build Clash for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  ANDROID_SDK_ROOT: ${{ env.RUNNER_TEMP }}/Android/Sdk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository without submodules
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Set up Git identity
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clean up existing submodule reference
        run: |
          rm -rf core/src/main/golang/clash
          git rm --cached -f core/src/main/golang/clash || true
          sed -i '/core\/src\/main\/golang\/clash/d' .gitmodules || true
          rm -rf .git/modules/core/src/main/golang/clash || true

      - name: Manually add submodule from Ieooo/clash
        run: |
          git submodule add https://github.com/Ieooo/clash.git core/src/main/golang/clash
          git submodule update --init --recursive

      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK
    
