name: Build Clash for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 先签出主仓库，不包括子模块
      - name: Checkout repository without submodules
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Set up Git identity
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clean up existing submodule reference
        run: |
          # 删除子模块目录（如果存在）
          rm -rf core/src/main/golang/clash
          # 从 Git index 中移除旧的子模块记录
          git rm --cached -f core/src/main/golang/clash || true
          # 从 .gitmodules 文件中删除关于该子模块的旧条目
          sed -i '/core\/src\/main\/golang\/clash/d' .gitmodules || true
          # 删除 Git 子模块缓存目录
          rm -rf .git/modules/core/src/main/golang/clash || true

      - name: Manually add submodule from Ieooo/clash
        run: |
          git submodule add https://github.com/Ieooo/clash.git core/src/main/golang/clash
          git submodule update --init --recursive

      # 此时可以再次签出子模块（已正确添加）
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget

      - name: Install Android SDK & NDK
        run: |
          yes | sudo apt-get install android-sdk
          yes | sudo apt-get install android-ndk

      - name: Set up Android environment variables
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "ndk.dir=$ANDROID_NDK_ROOT" >> local.properties

      - name: Install Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build Clash for Android
        run: |
          ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: clash-for-android-apk
          path: app/build/outputs/apk/**/*.apk
