name: Build Clash for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发构建

jobs:
  build:
    runs-on: ubuntu-latest  # 运行环境

    steps:
      - name: Checkout repository without submodules
        uses: actions/checkout@v3
        with:
          submodules: false  # 不签出子模块

      - name: Clean up old submodule references
        run: |
          # 彻底清理旧的子模块引用
          git submodule deinit -f core/src/main/golang/clash
          git rm -f core/src/main/golang/clash
          git commit -m "Remove old submodule commit reference"
          git push

      - name: Re-add submodule to latest commit from Ieooo/clash
        run: |
          # 删除缓存并重新添加正确的子模块引用
          rm -rf .git/modules/core/src/main/golang/clash
          git submodule add https://github.com/Ieooo/clash.git core/src/main/golang/clash
          git submodule update --init --recursive
          git commit -m "Re-add submodule with updated reference to Ieooo/clash"
          git push

      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true  # 这一步才会签出子模块

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget

      - name: Install Android SDK & NDK
        run: |
          yes | sudo apt-get install android-sdk
          yes | sudo apt-get install android-ndk

      - name: Set up Android environment variables
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "ndk.dir=$ANDROID_NDK_ROOT" >> local.properties

      - name: Install Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build Clash for Android
        run: |
          ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: clash-for-android-apk
          path: app/build/outputs/apk/**/*.apk
